name: バグ報告 (Bug Report)
description: 問題やバグを報告
title: "fix: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        バグの報告ありがとうございます！
        問題の解決を早めるため、以下の項目に入力してください。

  - type: textarea
    id: summary
    attributes:
      label: 概要 (Summary)
      description: どのような問題が発生しているか、簡潔に記述してください
      placeholder: "例: PDFを開いたときに、検索ハイライトがずれて表示される"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 再現手順 (Steps to Reproduce)
      description: 問題が発生するまでの手順を記述してください
      placeholder: |
        1. アプリを起動する
        2. 'example.pdf' を開く
        3. '検索' ボタンをクリックする
        4. エラーが表示される
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期待される動作 (Expected Behavior)
      description: 本来どうなるべきだったかを記述してください
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 実際の動作 (Actual Behavior)
      description: 実際に何が起きたかを記述してください
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 環境情報 (Environment)
      description: |
        OSのバージョン、アプリのバージョンなどを記述してください
        例: macOS 14.2, App Version 0.2.0
      placeholder: |
        - OS: 
        - App Version: 
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: 備考 (Notes)
      description: スクリーンショットやログがあれば貼り付けてください
    validations:
      required: false
