name: ドキュメント修正 (Documentation Update)
description: ドキュメントの不備や改善を提案
title: "docs: "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ドキュメントの改善提案ありがとうございます！

  - type: input
    id: target
    attributes:
      label: 対象ドキュメント (Target)
      description: 修正対象のファイル名やURL
      placeholder: README.md, docs/design.md
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: 変更内容 (Changes)
      description: 具体的な修正内容を記述してください
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 理由 (Reason)
      description: なぜ修正が必要なのか記述してください
    validations:
      required: false
